apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd
  name:  argocd
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: app
    app.kubernetes.io/name: app
  name:  app
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: monitoring
  name:  monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: redis
    app.kubernetes.io/name: redis
  name:  redis
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
---
