apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: redis-data-redis-replicas-0
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-redis-replicas-0
    namespace: redis
  capacity:
    storage: 8Gi
  hostPath:
    path: /tmp/hostpath-provisioner/redis/redis-data-redis-replicas-0
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: redis-data-redis-master-0
spec:
  accessModes:
  - ReadWriteOnce
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: redis-data-redis-master-0
    namespace: redis
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/hostpath-provisioner/redis/redis-data-redis-master-0
    type: ""
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  volumeMode: Filesystem