apiVersion: v1
kind: Namespace
metadata:
  name:  argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name:  app
---
apiVersion: v1
kind: Namespace
metadata:
  name:  monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name:  redis
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  name: ingress-nginx
---